version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
